export default {
    //PRODUCTS CUSTOM ERRORS
    PRODUCT_NOT_FOUND: 1,
    PRODUCT_NOT_CREATED: 2,
    PRODUCT_NOT_UPDATED: 3,
    PRODUCT_NOT_DELETED: 4,
    PRODUCT_NOT_FOUND_BY_ID: 5,
    PRODUCT_NOT_FOUND_BY_CODE: 6,

    //CART CUSTOM ERRORS
    CART_NOT_FOUND: 7,
    CART_NOT_CREATED: 8,
    CART_NOT_UPDATED: 9,
    CART_NOT_DELETED: 10,
    CART_NOT_FOUND_BY_ID: 11,
    CART_NOT_FOUND_BY_CODE: 12,

    // DB ERROR
    DB_ERROR: 13,

    // ROUTING ERROR
    ROUTING_ERROR: 14,

}